### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by JellyBrick** [organization/jda-nas-cxx#1]
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "lava-daemon-pool-native-udp-1-thread-1" J9VMThread:0x0000000000E40C00, omrthread_t:0x00007F6188014C08, java/lang/Thread:0x00000007E580CCB0, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x8B, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0xB35, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x00007F620DD51000, to:0x00007F620DD91000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.374962558 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=4096 (0x1000)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/udpqueue/natives/UdpQueueManagerLibrary.queuePacket(Native Method)
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/udpqueue/natives/UdpQueueManager.queuePacket(UdpQueueManager.java:75)
5XESTACKTRACE                   (entered lock: com/sedmelluq/discord/lavaplayer/udpqueue/natives/UdpQueueManagerLibrary@0x00000007E5808900, entry count: 1)
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/jdaudp/NativeAudioSendSystem.populateQueue(NativeAudioSendSystem.java:39)
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/jdaudp/NativeAudioSendFactory.populateQueues(NativeAudioSendFactory.java:93)
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/jdaudp/NativeAudioSendFactory$$Lambda$271/0000000000000000.run(Bytecode PC:4)
4XESTACKTRACE                at java/util/concurrent/Executors$RunnableAdapter.call(Executors.java:515(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/FutureTask.runAndReset(FutureTask.java:305)
4XESTACKTRACE                at java/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:835)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               (0x00007F6330D57EB2 [libj9prt29.so+0x4aeb2])
4XENATIVESTACK               (0x00007F6330D287C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007F6330D57F2E [libj9prt29.so+0x4af2e])
4XENATIVESTACK               (0x00007F6330D58024 [libj9prt29.so+0x4b024])
4XENATIVESTACK               (0x00007F6330D287C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007F6330D57D8B [libj9prt29.so+0x4ad8b])
4XENATIVESTACK               (0x00007F6330D54362 [libj9prt29.so+0x47362])
4XENATIVESTACK               (0x00007F6330D55134 [libj9prt29.so+0x48134])
4XENATIVESTACK               (0x00007F6330D287C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007F6330110FC6 [libj9dmp29.so+0x1afc6])
4XENATIVESTACK               (0x00007F633011115D [libj9dmp29.so+0x1b15d])
4XENATIVESTACK               (0x00007F6330D287C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007F633010D84D [libj9dmp29.so+0x1784d])
4XENATIVESTACK               (0x00007F6330108AFD [libj9dmp29.so+0x12afd])
4XENATIVESTACK               (0x00007F6330D287C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007F6330109EA0 [libj9dmp29.so+0x13ea0])
4XENATIVESTACK               (0x00007F633011355C [libj9dmp29.so+0x1d55c])
4XENATIVESTACK               (0x00007F63300FB04D [libj9dmp29.so+0x504d])
4XENATIVESTACK               (0x00007F63300FA645 [libj9dmp29.so+0x4645])
4XENATIVESTACK               (0x00007F6330D287C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007F63300FDD8B [libj9dmp29.so+0x7d8b])
4XENATIVESTACK               (0x00007F63300FDF1F [libj9dmp29.so+0x7f1f])
4XENATIVESTACK               (0x00007F63301152DB [libj9dmp29.so+0x1f2db])
4XENATIVESTACK               (0x00007F63314373E2 [libj9vm29.so+0x933e2])
4XENATIVESTACK               (0x00007F6330D287C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007F63314375F5 [libj9vm29.so+0x935f5])
4XENATIVESTACK               (0x00007F6330D27C8A [libj9prt29.so+0x1ac8a])
4XENATIVESTACK               (0x00007F63328E93C0 [libpthread.so.0+0x153c0])
4XENATIVESTACK               (0x00007F620DDC4AF3 [libudpqueue.so+0x33af3])
4XENATIVESTACK               (0x00007F620DDA6DD6 [libudpqueue.so+0x15dd6])
```

**Comment by JellyBrick** [comment]
# Debug build 

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "lava-daemon-pool-native-udp-1-thread-1" J9VMThread:0x0000000000D4BC00, omrthread_t:0x00007FF9F8005AA8, java/lang/Thread:0x00000006DDE67BF8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x64, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x718F, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x00007FFB370A1000, to:0x00007FFB370E1000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.264948166 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/udpqueue/natives/UdpQueueManagerLibrary.queuePacket(Native Method)
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/udpqueue/natives/UdpQueueManager.queuePacket(UdpQueueManager.java:75)
5XESTACKTRACE                   (entered lock: com/sedmelluq/discord/lavaplayer/udpqueue/natives/UdpQueueManagerLibrary@0x00000006DDE67C90, entry count: 1)
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/jdaudp/NativeAudioSendSystem.populateQueue(NativeAudioSendSystem.java:39)
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/jdaudp/NativeAudioSendFactory.populateQueues(NativeAudioSendFactory.java:93)
4XESTACKTRACE                at com/sedmelluq/discord/lavaplayer/jdaudp/NativeAudioSendFactory$$Lambda$271/0000000000000000.run(Bytecode PC:4)
4XESTACKTRACE                at java/util/concurrent/Executors$RunnableAdapter.call(Executors.java:515(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/FutureTask.runAndReset(FutureTask.java:305)
4XESTACKTRACE                at java/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:835)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               (0x00007FFB57DD4EB2 [libj9prt29.so+0x4aeb2])
4XENATIVESTACK               (0x00007FFB57DA57C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007FFB57DD4F2E [libj9prt29.so+0x4af2e])
4XENATIVESTACK               (0x00007FFB57DD5024 [libj9prt29.so+0x4b024])
4XENATIVESTACK               (0x00007FFB57DA57C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007FFB57DD4D8B [libj9prt29.so+0x4ad8b])
4XENATIVESTACK               (0x00007FFB57DD1362 [libj9prt29.so+0x47362])
4XENATIVESTACK               (0x00007FFB57DD2134 [libj9prt29.so+0x48134])
4XENATIVESTACK               (0x00007FFB57DA57C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007FFB571D9FC6 [libj9dmp29.so+0x1afc6])
4XENATIVESTACK               (0x00007FFB571DA15D [libj9dmp29.so+0x1b15d])
4XENATIVESTACK               (0x00007FFB57DA57C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007FFB571D684D [libj9dmp29.so+0x1784d])
4XENATIVESTACK               (0x00007FFB571D1AFD [libj9dmp29.so+0x12afd])
4XENATIVESTACK               (0x00007FFB57DA57C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007FFB571D2EA0 [libj9dmp29.so+0x13ea0])
4XENATIVESTACK               (0x00007FFB571DC55C [libj9dmp29.so+0x1d55c])
4XENATIVESTACK               (0x00007FFB571C404D [libj9dmp29.so+0x504d])
4XENATIVESTACK               (0x00007FFB571C3645 [libj9dmp29.so+0x4645])
4XENATIVESTACK               (0x00007FFB57DA57C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007FFB571C6D8B [libj9dmp29.so+0x7d8b])
4XENATIVESTACK               (0x00007FFB571C6F1F [libj9dmp29.so+0x7f1f])
4XENATIVESTACK               (0x00007FFB571DE2DB [libj9dmp29.so+0x1f2db])
4XENATIVESTACK               (0x00007FFB5C5743E2 [libj9vm29.so+0x933e2])
4XENATIVESTACK               (0x00007FFB57DA57C3 [libj9prt29.so+0x1b7c3])
4XENATIVESTACK               (0x00007FFB5C5745F5 [libj9vm29.so+0x935f5])
4XENATIVESTACK               (0x00007FFB57DA4C8A [libj9prt29.so+0x1ac8a])
4XENATIVESTACK               (0x00007FFB5DA263C0 [libpthread.so.0+0x153c0])
```
